server:
  port: 8080
tomcat:
    max-http-form-post-size: 81920
spring:
  application:
    # 应用的名称
    name: reggie_take_out
  datasource:
    # druid数据库连接
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: mq3670340
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  cache:
    redis:
      time-to-live: 1800000 #设置缓存有效期

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射 address_book ---> AddressBook
    map-underscore-to-camel-case: true
    #日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #该配置完成后，每个模型类的主键ID策略都将成为assign_id
      id-type: ASSIGN_ID
reggie:
  path: D:\IDEA\mq\reggie\reggie\src\图片资源\
